theme: jekyll-theme-minimal
title: Laura Santer
description: Laura Santer's Homepage
logo:https://www.google.com/search?q=rescue+puppies&tbm=isch&ved=2ahUKEwj8lr-n7YT2AhUSmnIEHT06AVwQ2-cCegQIABAA&oq=rescue+puppies&gs_lcp=CgNpbWcQAzIECAAQQzIECAAQQzIECAAQQzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgAELEDEEM6CAgAEIAEELEDOgsIABCABBCxAxCDAToICAAQsQMQgwE6BAgAEANQjwlYo09g2VBoA3AAeACAAYUBiAGPCZIBBDE3LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ7ABAMABAQ&sclient=img&ei=kEINYvyOGJK0ytMPvfSE4AU&bih=892&biw=1504&rlz=1C1JZAP_enUS888US888#imgrc=XaDz4YvrFC0whM
github:
  is_project_page: false
  is_user_page: false
